name: SSH

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v4

      - name: Setup Debug Session
        uses: csexton/debugger-action@master

      - name: Compress Upload folder
        run: |
          mkdir -p artifacts
          zip -r artifacts/Upload.zip ./Upload

      - name: Upload What I Want
        uses: actions/upload-artifact@v4
        with:
          name: My Temporary Files
          path: |
            path: artifacts/Upload.zip
          retention-days: 90
